#!/usr/bin/env python3
"""Regenerate docs/design-docs/subagents.md from .claude/agents/*.md frontmatter.

Reads each subagent file's YAML frontmatter (name, description, tools,
can_modify) and emits a markdown table. Append-only sections in the existing
file (anything after the auto-generated table) are preserved.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Iterator

AGENT_DIR = Path(".claude/agents")
INDEX_PATH = Path("docs/design-docs/subagents.md")
MARKER = "<!-- sn-init:auto-table -->"


def parse_frontmatter(text: str) -> dict:
    match = re.match(r"^---\n(.*?)\n---", text, flags=re.DOTALL)
    if not match:
        return {}
    out: dict = {}
    for line in match.group(1).splitlines():
        m = re.match(r"^([a-zA-Z_][a-zA-Z0-9_]*)\s*:\s*(.*?)\s*$", line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2)
        if raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            if inner:
                out[key] = [s.strip().strip('"').strip("'") for s in inner.split(",")]
            else:
                out[key] = []
        elif raw == "":
            out[key] = ""
        else:
            out[key] = raw.strip('"').strip("'")
    return out


def collect_agents(root: Path) -> Iterator[dict]:
    agents_dir = root / AGENT_DIR
    if not agents_dir.exists():
        return
    for path in sorted(agents_dir.rglob("*.md")):
        if path.name == "README.md":
            continue
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        # The frontmatter `name:` is authoritative — files prefixed `sn-`
        # already carry their full callable name (e.g. `sn-knowledge-curator`).
        yield {
            "name": fm.get("name", path.stem),
            "description": fm.get("description", ""),
            "tools": fm.get("tools", []),
            "can_modify": fm.get("can_modify", []),
            "path": str(path.relative_to(root)),
        }


def render_table(records: list[dict]) -> str:
    lines = [
        MARKER,
        "",
        "| Name | Tools | Can modify | Description |",
        "|---|---|---|---|",
    ]
    for r in records:
        tools = ", ".join(r["tools"]) if isinstance(r["tools"], list) else r["tools"]
        modify = ", ".join(r["can_modify"]) if isinstance(r["can_modify"], list) else r["can_modify"]
        desc = (r["description"] or "").replace("|", "\\|")
        lines.append(f"| `{r['name']}` | {tools or '—'} | {modify or '—'} | {desc} |")
    lines.append("")
    return "\n".join(lines)


def merge(existing: str, table: str) -> str:
    """Replace the auto-table block; preserve anything after the block."""
    if MARKER in existing:
        head = existing.split(MARKER)[0].rstrip()
        # Find the end of the previous table (first blank line after MARKER).
        rest = existing.split(MARKER, 1)[1]
        rest_lines = rest.splitlines()
        # Skip lines that look like the prior table (until a blank line preceding non-table content).
        cut = 0
        for i, ln in enumerate(rest_lines):
            if ln.strip() == "" and i > 2:
                cut = i
                break
        tail = "\n".join(rest_lines[cut:])
        return head + "\n\n" + table + tail
    return existing.rstrip() + "\n\n" + table


def main(argv: list[str] | None = None) -> int:
    root = Path.cwd()
    args = argv if argv is not None else sys.argv[1:]
    if args and args[0] in ("-h", "--help"):
        print("usage: gen_subagent_index.py")
        return 0

    records = list(collect_agents(root))
    table = render_table(records)
    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    full_path = root / INDEX_PATH
    existing = full_path.read_text(encoding="utf-8") if full_path.exists() else (
        "# Subagent library\n\nIndex of subagents available in `.claude/agents/`. Auto-generated by\n"
        "`make subagent-index` (scripts/gen_subagent_index.py).\n\n"
    )
    full_path.write_text(merge(existing, table), encoding="utf-8")
    print(f"sn-init: wrote {INDEX_PATH} ({len(records)} subagents)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
